### PR TITLE
Bound the hideNotification method triggered by onClick

### LINKED ISSUE #4592: Error message 'Uncaught TypeError: Cannot read properties of undefined (reading 'props')' appears in the console when closing notification messages
**Description**:
Error message 'Uncaught TypeError: Cannot read properties of undefined (reading 'props')' appears in the console when closing notification messages

**Expected behavior**:
No errors

**To Reproduce**:
1. Open PDP
2. Add product to cart
4. Click on Cross in notification message

**Actual result**:
Error message 'Uncaught TypeError: Cannot read properties of undefined (reading 'props')' appears in the console
Screenshot 2022-03-28 at 14 03 33

**Additional context**:
The same situation with all notification messages

### PR DESCRIPTION
**Pull request by AzizKHAN030**
**Related issue(s):**
* Fixes #4592 

**Problem:**
* TypeError appeared when closing the notification by clicking the close button

**In this PR:**
* Bound the hideNotification method where it's been called

### CODE REVIEW

File: packages/scandipwa/src/component/Notification/Notification.component.js [hunk 1]
```diff
@@ -110,7 +110,14 @@ export class Notification extends PureComponent {
 
         return (
             <div block="Notification" mods={ mods } ref={ this.notification } id={ id }>
-                <button block="Notification" elem="Button" onClick={ this.hideNotification }>Close</button>
+                <button
+                  block="Notification"
+                  elem="Button"
+                // eslint-disable-next-line react/jsx-no-bind
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/Notification/Notification.component.js:116]: Please don't disable eslint for no reason.
Better ask about it first.

File: packages/scandipwa/src/component/Notification/Notification.component.js [hunk 2]
```diff
@@ -110,7 +110,14 @@ export class Notification extends PureComponent {
...
+                  onClick={ this.hideNotification.bind(this) }
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/Notification/Notification.component.js:117]: You can bind a method like this:
```javascript
hideNotification = this.hideNotification.bind(this);
```
For more examples see:
* https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/component/CarouselScroll/CarouselScroll.component.js#L52-L54
* https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/component/CartCoupon/CartCoupon.component.js#L42-L48

**Review by zans-laksa — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/component/Notification/Notification.component.js (hunk 2 above)
Comment (AzizKHAN030) [reply packages/scandipwa/src/component/Notification/Notification.component.js]: Thank you, corrected!

**Review by zans-laksa — APPROVED** [review]
