### PR TITLE
Supplemented missing query with the condition

### LINKED ISSUE #2046: small_image.jpg is loader instead of image.jpg on the product page
**Description**:
small_image.jpg is loader instead of image.jpg on the product page

**Expected behavior**:
image.jpg is loaded

**Screenshots, Video, Logs**
image (1)

**To Reproduce**:
1. Open product page that does not have any images assigned
2. Notice the issue described above

### PR DESCRIPTION
**Pull request by winniepukki**
Fixes #2046

### CODE REVIEW

File: packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ export class ProductGalleryContainer extends PureComponent {
             areDetailsLoaded,
             product: {
                 media_gallery_entries: mediaGallery = [],
-                [THUMBNAIL_KEY]: { url } = {},
```
Comment (yeegor) [inline packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js:104]: I think this modification does not do what you expect it to.
Both `IMAGE_TYPE` and `THUMBNAIL_KEY` variables have constant values here (and everywhere else), they come from the `.config.js` file. Hence, `IMAGE_TYPE || THUMBNAIL_KEY` will __always__ return `IMAGE_TYPE`.

**Review by yeegor — CHANGES_REQUESTED** [review]

**Review by yeegor — APPROVED** [review]
