### PR TITLE
error caused because default func type is null

### LINKED ISSUE #4967: Can't add product to cart from compare list
**Description**:
Can't add product to cart from compare list

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Open PDP
2. Add product to compare list
3. Open Compare list
4. Click on Add to cart

**Actual result**:
Product isn't added to cart
Error message 'Uncaught (in promise) TypeError: a is not a function' appears in the console
Screenshot 2022-06-27 at 11 50 42

### PR DESCRIPTION
**Pull request by AzizKHAN030**
**Related issue(s):**
* Fixes #4967 

**Problem:**
* Error was thrown because updateSelectedValues func, this func is needed for PDP, if it is not passed then it's null, so null can't be called

**In this PR:**
* added check

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Adding product without options - ok
2. Nothing happens when adding product with options to cart from compare list
https://vimeo.com/724421609/bbe5849927
**Expected result:**
User is redirected to PDP and notification message appears

**Comment by AzizKHAN030** [comment]
This issue is not related to the current, and this problem is being fixed by @neeeeecka in one of his tasks

File: packages/scandipwa/src/component/AddToCart/AddToCart.container.js [hunk 1]
```diff
@@ -98,7 +98,10 @@ export class AddToCartContainer extends PureComponent {
 
     async addProductToCart() {
         const { product, addToCart, updateSelectedValues } = this.props;
-        await updateSelectedValues();
+
+        if (updateSelectedValues !== null) {
+            await updateSelectedValues();
+        }
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/AddToCart/AddToCart.container.js:104]: !updateSelectedValues won't be same?

**Review by AleksandrsKondratjevs — APPROVED** [review]
