### PR TITLE
issue-2223 - Fix incorrect message appear on error password reset

### LINKED ISSUE #2223: Wrong error is displayed on reset password page if user tried to submit password with less than needed different classes of characters
**Description**:
Wrong error is displayed on reset password page if user tried to submit password with less than needed different classes of characters

**Expected behavior**:
Error message 'Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters. ' is displayed

**To Reproduce**:
1. Open website
2. Open Sign in form
3. Tap 'forgot password'
4. Enter your email
5. Tap 'Send reset link'
6. Open received email with a reset link
7. Enter new/confirm password (use 1 or 2 different classes of characters, for example -scandipwa123
8. Tap 'Update password'

**Actual result**:
Error message 'Error!Something went wrong'
image

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
Fixes #2223 

related: https://github.com/scandipwa/customer-graph-ql/pull/18

### CODE REVIEW

File: packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js [hunk 1]
```diff
@@ -142,7 +142,10 @@ export class MyAccountDispatcher {
             /** @namespace Store/MyAccount/Dispatcher/resetPasswordFetchMutationThen */
             ({ s_resetPassword: { status } }) => dispatch(updateCustomerPasswordResetStatus(status)),
             /** @namespace Store/MyAccount/Dispatcher/resetPasswordFetchMutationError */
-            () => dispatch(updateCustomerPasswordResetStatus('error'))
+            (errors) => {
+                const [{ message }] = errors;
```
Comment (zans-laksa) [inline packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js:146]: `errors` is array only if it is graphql error. if promise catches js error, then it will be a regular Error object.
You can use `getErrorMessage` from the `src/util/Request/Error.js`

**Review by zans-laksa — CHANGES_REQUESTED** [review]
Code review didn't pass.

**Review by zans-laksa — APPROVED** [review]
Code review passed.

**Review by yeegor — APPROVED** [review]
