### PR TITLE
issue-3676 - Check for value on dropdown select option for native input

### LINKED ISSUE #3676: Order of products is not changed on PLP if user select new in 'Sort by' on mobile
**Description**:
Order of products is not changed if user select new in 'Sort by' on mobile

**Expected behavior**:
Order of products is changed if user select new in 'Sort by' on mobile

**Screenshots, Video, Logs**
https://drive.google.com/file/d/17fMtCjx2ZJe6ASB7w732VtJP_nNlHvSc/view?usp=sharing

**To Reproduce**:
1. Open any PLP on mobile
2. Tap on Sort
3. Select any other type of sorting
4. Observe order of products

**Actual result**:
Order of products is not changed if user select new in 'Sort by' on mobile

### LINKED ISSUE #3678: User can not buy configurable product dropdown options on mobile
**Description**:
User can not buy configurable product with color + dropdown required options **on mobile**
If user select first dropdown option, then color options blocked
If user select first color option then dropdown available, but error message appear after user select dropdown and tap on 'Add to cart' (Error message: 'You need to choose options to your item')
Everything ok on desktop

**Expected behavior**:
User can select options and finish purchase

**Screenshots, Video, Logs**
https://drive.google.com/file/d/1X37fO-AmpYBf1jujbnGlT2iFrqmX7Ril/view?usp=sharing

**To Reproduce**:
1. Open products with color and dropdown options
https://master.d25kd40decjpue.amplifyapp.com/default/kids/8conf.html
https://master.d25kd40decjpue.amplifyapp.com/default/baggini-bagpack-108.html
https://master.d25kd40decjpue.amplifyapp.com/default/config-product-with-required-radio-buttons.html
product with only dropdown https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/baggini-config-max.html 
2. Select options
3. Add to cart if button enabled

**Actual result**:
User can not buy configurable product with color + dropdown required options **on mobile**

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
**Related issue(s):**
* Fixes #3676 
* Fixes #3678

**Problem:**
* dropdowns on mobile not working

**In this PR:**
* handle native select option to get value from in on change instead of full object

### CODE REVIEW

File: packages/scandipwa/src/component/PureForm/FieldSelect/FieldSelect.component.js [hunk 1]
```diff
@@ -76,6 +76,8 @@ export class FieldSelect extends PureComponent {
               { ...attr }
               // eslint-disable-next-line @scandipwa/scandipwa-guidelines/jsx-no-props-destruction
               { ...events }
+              // eslint-disable-next-line react/jsx-no-bind
+              onChange={ (elem) => handleSelectListOptionClick(elem) }
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/PureForm/FieldSelect/FieldSelect.component.js:80]: Please pass the callback directly instead of making another arrow function.

**Review by zans-laksa — CHANGES_REQUESTED** [review]

**Review by zans-laksa — APPROVED** [review]
