### PR TITLE
issue-2683 - Fix equal price issue

### LINKED ISSUE #2683: Price incl.tax = excl.tax for all product on all pages
**Description**:
Price incl.tax = excl.tax for all product on all pages

**Expected behavior**:
Price incl.tax = price excl.tax + tax

**To Reproduce**:
1. Open PLP
2. Open PDP
3. Add product to cart

**Actual result**:
Price incl.tax = excl.tax for all product on all pages

**Additional context**:
on Demo:
Prices incl. and excl. tax are displayed correctly on PLP 
Price incl.tax = excl.tax on PDP
image

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
Fixes #2683

### CODE REVIEW

File: packages/scandipwa/src/component/ProductActions/ProductActions.container.js [hunk 1]
```diff
@@ -436,7 +438,7 @@ export class ProductActionsContainer extends PureComponent {
             return this._getCustomPrice(selectedLinkPrice, selectedLinkPrice, true);
         }
 
-        if (product.options) {
+        if (Object.keys(options).length !== 0) {
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/ProductActions/ProductActions.container.js:441]: But what if `product.options` is undefined or null?

**Review by zans-laksa — CHANGES_REQUESTED** [review]
Code review didn't pass.

**Review by zans-laksa — APPROVED** [review]
Code review passed.
