### PR TITLE
MyAccount address allowed country fix

### LINKED ISSUE #2566: Ooops page opens when opening Edit address form in my account if this country was removed from list of Allowed countries
**Description**:
Ooops page opens when opening Edit address form in my account if this country was removed from list of Allowed countries

**Expected behavior**:
Edit address form opens but the country field is empty
image

**To Reproduce**:
1. Log in poi@poi.po/Scandipwa123
2. Open Address book
3. Click on 'edit address' for default billing/shipping address

**Actual result:**:
Ooops page opens
image
image

**Notes: **
It happens if user added an address and then this country removed from the list of Allowed Countries (Open Admin panel -> Go to Stores -> Configuration -> General -> General)

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
fixes #2566

### CODE REVIEW

File: packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js [hunk 1]
```diff
@@ -38,17 +38,16 @@ export class MyAccountAddressForm extends FieldForm {
...
                 city = ''
             }
         } = props;
 
-        const countryId = country_id || default_country;
-        const country = countries.find(({ id }) => id === countryId);
-        const isStateRequired = country.is_state_required;
+        const country = countries.find(({ id }) => id === country_id);
+        const countryId = country ? country_id : '';
+        const isStateRequired = country ? country.is_state_required : false;
```
Comment (IvansZuks) [inline packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js:50]: Please destruct country

**Review by IvansZuks — CHANGES_REQUESTED** [review]

**Comment by AleksandrsKondratjevs** [comment]
@IvansZuks Hello! 
Found a bug on checkout after this PR so kind fixed it and code changed a bit. Can you please take a look again at it?

**Review by IvansZuks — APPROVED** [review]
