### PR TITLE
Fixes Never-Ending loader if user canceled second file input

### LINKED ISSUE #3511: Never-ending loader instead file input on PDP if user canceled the second try to upload file
**Description**:
Never-ending loader instead file input on PDP if user canceled the second try to upload file

**Expected behavior**:
Name of the first uploaded file is displayed in file input

**To Reproduce**:
1. Open product with file option - https://master.d25kd40decjpue.amplifyapp.com/default/women/women-shoes/flip-flops/havaianas-green.html
2. Click on file input -> Select file -> Upload file
3. Click on file input -> Click on cancel 

**Actual result**:
Never-ending loader instead file input
Error message 'Uncaught TypeError: Cannot read properties of undefined (reading 'name')' appears in the console
https://drive.google.com/file/d/1RiT3RS1ccTUoPyKAVXeLZqzsD0Nx7ubI/view?usp=sharing
Screenshot 2021-11-17 at 08 28 07

### PR DESCRIPTION
**Pull request by SalimMersally**
**Related issue(s):**
* Fixes #3511 

**Problem:**
* File input display an infinite loader (+ and error in console) if user canceled the input on the second time

**In this PR:**
* Fixes the error but checking if there is a file input or not

### CODE REVIEW

File: packages/scandipwa/src/component/FieldFile/FieldFile.container.js [hunk 1]
```diff
@@ -55,8 +55,17 @@ export class FieldFileContainer extends PureComponent {
         if (this.fieldRef) {
             const { files } = this.fieldRef;
             this.setState({ isLoading: true });
+            const { name } = files[0] ? files[0] : '';
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/FieldFile/FieldFile.container.js:58]: In case if files[0] is undefined you will be getting undefiend in name, because 
` const { name } = '';

So just `files[0] || {}`

**Review by AleksandrsKondratjevs — CHANGES_REQUESTED** [review]
