### PR TITLE
fixed loading state in overlay sign in form, removed overlay's Loader…

### LINKED ISSUE #4505: Loader is missing for Sign in form in checkout when logging in
**Description**:
Loader is missing for Sign in form in checkout when logging in 

**Expected behavior**:
Add loader for Sign in form in checkout 
Screenshot 2022-03-18 at 13 16 28 (2)

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Go to checkout
4. Enter registred email
5. Enter password
6. Click on Sign in

**Actual result**:
Loader is missing

### PR DESCRIPTION
**Pull request by AzizKHAN030**
… component

**Related issue(s):**
* Fixes #4505 

**Problem:**
* Missing Loader for sign in for in checkout page and finally loader being displayed in the sign-in overlay in the main page

**In this PR:**
* Removed Overlay's Loader because now sign-in component has itself

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1. Two loaders are displayed on /customer/account/login page when logging in
Screenshot 2022-03-23 at 10 31 44 (2)

File: packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js [hunk 1]
```diff
@@ -185,16 +185,17 @@ export class MyAccountOverlay extends PureComponent {
               isCheckout={ isCheckout }
               setLoadingState={ setLoadingState }
               onSignIn={ onSignIn }
+              isLoading={ false }
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js:188]: What is the point in this case? Should it be always false? Maybe then add default prop to MyAccountSignIn if it is not passed, then be false?

**Review by AleksandrsKondratjevs — CHANGES_REQUESTED** [review]

**Comment by AzizKHAN030** [comment]
Access this pull request here: https://pr-4539.d25kd40decjpue.amplifyapp.com/

Seems like amplify stuck on sending comment but actually built

**Review by AleksandrsKondratjevs — APPROVED** [review]
