### PR TITLE
Fix #2569 - Improve stock status detection based on variants presence

### LINKED ISSUE #2569: Status 'Out of stock' is displayed for all products 'In stock' except config product
**Description**:
Status 'Out of stock' is displayed for all products 'In stock' except config product

**Expected behavior**:
Correct status is displayed:
If product in stock - Status 'In Stock' is displayed
If product out of stock - Status 'Out of stock' is displayed

**To Reproduce**:
1. Open simple product -https://master.d25kd40decjpue.amplifyapp.com/default/product-y.html
2. Open bundle product - https://master.d25kd40decjpue.amplifyapp.com/default/bundle-product2.html
3. Open virtual product -https://master.d25kd40decjpue.amplifyapp.com/default/8vir.html
4. Open Downloaded product - https://master.d25kd40decjpue.amplifyapp.com/default/downloadable.html
5. Open grouped product - https://master.d25kd40decjpue.amplifyapp.com/default/28-grouped-product.html

**Versions**:
Status 'Out of stock' is displayed for all products 'In stock' except config product
image

**Additional context**:
I suppose this issue appears after this fix #2405

### PR DESCRIPTION
**Pull request by tatiana-scandi**

### CODE REVIEW

File: packages/scandipwa/src/route/ProductPage/ProductPage.container.js [hunk 1]
```diff
@@ -495,7 +495,7 @@ export class ProductPageContainer extends PureComponent {
         const currentVariantIndex = this.getConfigurableVariantIndex(variants);
         const variant = variants && variants[currentVariantIndex];
 
-        if (variants) {
+        if (variants?.length > 0) {
```
Comment (yeegor) [inline packages/scandipwa/src/route/ProductPage/ProductPage.container.js:498]: You could have just used `if (variants?.length) { ... }`
But this option is fine as well.

**Review by yeegor — APPROVED** [review]
