### PR TITLE
issue-2628 - Rework adding to localstorage products data

### LINKED ISSUE #2628: localStorage is overflowed - user can't add product to cart
**Description**:
localStorage is overflowed - user can't add product to cart. Error message 'Failed to execute ‘setItem’ on ‘Storage’: Setting the value of ‘cart_totals’ exceeded the quota' appears 

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/ciunas.html 
2. Select attributes
3. Click on Add to cart

**Actual result:**:
Error message 'Failed to execute ‘setItem’ on ‘Storage’: Setting the value of ‘cart_totals’ exceeded the quota' appears BUT we received graphql with updated cart
image

**Additional context**:
Safari: Ooops page opens and errors in the console 
image

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
Fixes #2628

Localstorage max size is 5mb. In case if we add https://master.d25kd40decjpue.amplifyapp.com/default/ciunas.html into cart or just visit it so it is automatically added into recentView we are getting error, because localstorage is overcrowded. Products has a lot of options to select from => a lot of variations is added into cart_totals for this products. 
localstorage

1. Add into cart_totals not all variants, but only 1 that is shows in cart, since we don't use others.
2. For recently viewed products we can save only preview of product, when we enter page with recently viewed product widget we can see those products, we can click on them, but options are loading from BE, because we are not holding them in localstorage. (while we waiting for full product data, we are just showing placeholders under name/price)

### CODE REVIEW

File: packages/scandipwa/src/component/ProductCard/ProductCard.component.js [hunk 1]
```diff
@@ -419,7 +425,19 @@ export class ProductCard extends PureComponent {
     }
 
     renderMainDetails() {
-        const { product: { name } } = this.props;
+        const { product: { name }, layout } = this.props;
+
+        if (layout === GRID_LAYOUT) {
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/ProductCard/ProductCard.component.js:430]: A lot of errors in console because  <a> cannot appear as a descendant of <a>. We render it only on PLP when layout is list mode

Comment (yeegor) [reply packages/scandipwa/src/component/ProductCard/ProductCard.component.js:430]: Very good

File: packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.container.js [hunk 2]
```diff
@@ -41,6 +48,19 @@ export class RecentlyViewedWidgetContainer extends PureComponent {
...
+        const {
+            shouldBeUpdated,
+            updateRecentViewedProductsInfo,
+            recentProducts,
+            store
+        } = this.props;
+
+        if (shouldBeUpdated && Object.entries(recentProducts).length !== 0) {
+            updateRecentViewedProductsInfo({ recentProducts, store });
+        }
```
Comment (yeegor) [inline packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.container.js:61]: What is the meaning of the `Object.entries` call here?

**Review by yeegor — APPROVED** [review]
