### PR TITLE
#4812 adjusted form width when ratings are disabled

### LINKED ISSUE #4812: Review pop-up looks ugly if all ratings are disabled or not assigned to the store
**Description**:
Review pop-up looks ugly if all ratings are disabled or not assigned to the store

**Expected behavior**:
Fields are displayed on all widths of pop-up
Screenshot 2022-05-23 at 11 03 37

**To Reproduce**:
Admin panel:
1. Open Stores -> Rating
2. Disable all Ratings or not assign these to store X
3. Save
4. Clear cache

FE:
5. Open PDP on store X
6. Open Review tab
7. Click on Write a Review

**Actual result**:
Pop up looks ugly
Screenshot 2022-05-23 at 11 03 37

### PR DESCRIPTION
**Pull request by MaritaKochua**
**Related issue(s):**
* Fixes #4812 

**Problem:**
* Popup looked off when ratings were disabled.

**In this PR:**
* Made form spread 3 columns only when it's the first child, thus making it fill the entire popup.

### CODE REVIEW

File: packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js [hunk 1]
```diff
@@ -120,12 +120,14 @@ export class ProductReviewForm extends PureComponent {
...
-                    { this.renderReviewRating() }
-                </div>
+                { reviewRatings.length > 0 && (
+                    <div
+                      block="ProductReviewForm"
+                      elem="RatingWrapper"
+                    >
+                        { this.renderReviewRating() }
+                    </div>
+                ) }
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js:130]: Please move this one to the separate render method.

**Review by zans-laksa — CHANGES_REQUESTED** [review]

**Review by zans-laksa — APPROVED** [review]

**Comment by carinadues** [comment]
Looking good! Let's just improve one more thing:

Please increase the top margin of the Submit Review button, to be the same spacing as we have now between the other fields.

image

File: packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss [hunk 2]
```diff
@@ -18,6 +18,9 @@
         }
     }
 
+    display: flex;
+    flex-direction: column;
+
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss:23]: Please put properties before any nested block.

**Review by zans-laksa — CHANGES_REQUESTED** [review]

**Review by zans-laksa — APPROVED** [review]
