### PR TITLE
put defaultChecked value in defaultChecked prop for type radio 

### LINKED ISSUE #4500: User can't select radio buttons option from the first time for bundle or products with not required customizable options
**Description**:
User can't select radio buttons option from the first time for bundle or products with not required customizable options

**Expected behavior**:
Option is selected from the first try 

**To Reproduce**:
1. Open Bundle product with radio buttons option (where one of option is selected by default) or product with not required customizable option - type radio button - https://master.d25kd40decjpue.amplifyapp.com/default/bundle-product-with-required-radio-buttons.html
2. Select not default option X
3. Select again the same option
4. Select another option Y

**Actual result**:
2. and 4 step: Default option Z is selected when choosing not default option X or Y for the first time. 
3. Option X is selected
https://drive.google.com/file/d/1Cfq7n9TfbyBlFnIxt9WqxbalFwQ_pYz8/view?usp=sharing

**Notes:**
Can't unselect default option in checkbox options

### PR DESCRIPTION
**Pull request by AzizKHAN030**
**Related issue(s):**
* Fixes #4500 

**Problem:**
* The checkboxes and radio inputs didn't checked from the first time

**In this PR:**
* Replaced defaultChecked value in defaultChecked prop as it should be.

### CODE REVIEW

File: packages/scandipwa/src/component/Field/Field.component.js [hunk 1]
```diff
@@ -219,6 +219,7 @@ export class Field extends PureComponent {
                   { ...inputEvents }
                   // shipping options have checked attr assigned so prioritize its value
                   checked={ checked || isChecked }
+                  defaultChecked={ defaultChecked }
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/Field/Field.component.js:222]: the defaultChecked prop is used for uncontrolled components.
You shouldn't mix checked and defaultChecked props.
Please improve the logic that defines the checked state instead.

**Review by zans-laksa — CHANGES_REQUESTED** [review]

**Review by zans-laksa — APPROVED** [review]
