### PR TITLE
SSR RenderWhenVisible Component Fix

### LINKED ISSUE #1929: SSR - RenderWhenVisible
**Description**:
The Component RenderWhenVisible is not working correctly on rendertron/prerender. The RenderWhenVisible prevents it from showing all data for those programs.

There needs to be a function there see if is a crawler that visiting the website, and removes the RenderWhenVisible component.

**Expected behavior**:
Showing all data for rendertron/prerender

**Versions**:
- ScandiPWA: 3.2.4

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #1929
Added some checks in order to determine whether component is prerendered or should be displayed only if visible.
Added check whether window and document objects are present and a crawler ua check from task comment.

This branch parent is another PR, since there is another task for RenderWhenVisible component, which is solved but not merged.
See #2155

### CODE REVIEW

File: packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js [hunk 1]
```diff
@@ -52,16 +51,31 @@ export class RenderWhenVisible extends PureComponent {
...
+        if (!wasVisible && isVisible) {
             this.setState({ wasVisible: true });
         }
     };
 
+    isSSR() {
+        return !globalThis.window || !globalThis.window.document;
+    }
+
+    isCrawler() {
```
Comment (yeegor) [inline packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js:71]: 1. Consider making this an util. It is not strictly related to this component. We may need to determine whether user is crawler somewhere else in the future :)
2. Please have this regex declared separately, outside the function scope, there is no need to re-declare it each time this function is called.

File: packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js [hunk 2]
```diff
@@ -52,16 +51,31 @@ export class RenderWhenVisible extends PureComponent {
...
+        const { wasVisible } = this.state;
+
+        if (!wasVisible && isVisible) {
             this.setState({ wasVisible: true });
         }
     };
 
+    isSSR() {
+        return !globalThis.window || !globalThis.window.document;
+    }
```
Comment (yeegor) [inline packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js:69]: Same as below - consider making this an util.

**Review by yeegor — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js (hunk 1 above)
Comment (zans-laksa) [reply packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js]: Done

File: packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js (hunk 2 above)
Comment (zans-laksa) [reply packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js]: Done

File: packages/scandipwa/src/util/Browser/Browser.js [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
...ex|Adidxbot|blekkobot|ezooms|dotbot|Mail.RU_Bot|discobot|heritrix|findthatfile|europarchive.org|NerdByNature.Bot|sistrix crawler|ahrefsbot|Aboundex|domaincrawler|wbsearchbot|summify|ccbot|edisterbot|seznambot|ec2linkfinder|gslfbot|aihitbot|intelium_bot|facebookexternalhit|yeti|RetrevoPageAnalyzer|lb-spider|sogou|lssbot|careerbot|wotbox|wocbot|ichiro|DuckDuckBot|lssrocketcrawler|drupact|webcompanycrawler|acoonbot|openindexspider|gnam gnam spider|web-archive-net.com.bot|backlinkcrawler|coccoc|integromedb|content crawler spider|toplistbot|seokicks-robot|it2media-domain-crawler|ip-web-crawler.com|siteexplorer.info|elisabot|proximic|changedetection|blexbot|arabot|WeSEE:Search|niki-bot|CrystalSemanticsBot|rogerbot|360Spider|psbot|InterfaxScanBot|Lipperhey SEO Service|CC Metadata Scaper|g00g1e.net|GrapeshotCrawler|urlappendbot|brainobot|fr-crawler|binlar|SimpleCrawler|Livelapbot|Twitterbot|cXensebot|smtbot|bnf.fr_bot|A6-Indexer|ADmantX|Facebot|Twitterbot|OrangeBot|memorybot|AdvBot|MegaIndex|SemanticScholarBot|ltx71|nerdybot|xovibot|BUbiNG|Qwantify|archive.org_bot|Applebot|TweetmemeBot|crawler4j|findxbot|SemrushBot|yoozBot|lipperhey|y!j-asr|Domain Re-Animator Bot|AddThis|HeadlessChrome)/i;
```
Comment (yeegor) [inline packages/scandipwa/src/util/Browser/Browser.js:17]: Each time `isCrawler` is called, this HUGE regexp will be re-declared.
By that, I mean that memory will be allocated, it will get generated, and then it'll be garbage-collected, so that the memory gets reclaimed by the engine.
It's better to declare it once and for all times, e.g. on the outer level of the module. And then use it within the function. This way, we'll save a bit of performance and will follow better coding practices :)

**Review by yeegor — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/util/Browser/Browser.js (hunk 3 above)
Comment (zans-laksa) [reply packages/scandipwa/src/util/Browser/Browser.js]: Got it. Done.
