### PR TITLE
SWPWA-2153 - Field validation is missing

### LINKED ISSUE #2153: Field validation is missing
**Description**:
Field validation is missing

**Expected behavior**:
Validation is present 

**To Reproduce**:
1. Open login overlay
2. Make sure all fields are empty
3. Click on login
4. Notice there is not field validation

### PR DESCRIPTION
**Pull request by robertsbriedis**
- Fixes #2153.

### CODE REVIEW

File: packages/scandipwa/src/component/Form/Form.component.js [hunk 1]
```diff
@@ -42,21 +42,32 @@ export class Form extends PureComponent {
...
 
         const refMap = {};
 
         const children = Form.cloneChildren(
             propsChildren,
             (child) => {
                 const { props: { name } } = child;
+                const { message } = Object.keys(refMapState).length
+                    ? Form.validateField(child, refMapState)
+                    : {};
```
Comment (yeegor) [inline packages/scandipwa/src/component/Form/Form.component.js:57]: Re-calculating Object.keys during each iteration of this callback is redundant. Please, calculate it only once.

**Review by yeegor — CHANGES_REQUESTED** [review]
Seems OK, minor improvement required.

File: packages/scandipwa/src/component/Form/Form.component.js (hunk 1 above)
Comment (robertsbriedis) [reply packages/scandipwa/src/component/Form/Form.component.js:57]: Forgot to mention, that this is just a quick issue fix improvement, as time was limited, overall the whole logic for the component does some conflicts by itself.

`...Form.cloneAndValidateChildren(children, refMap),
...Form.updateChildrenRefs(props, state)`

Like these, both methods return children's prop, so the second overrides the first one, and really hard to understand what's even happening there.
