### PR TITLE
Compare Page Out Of Stock Product Fix

### LINKED ISSUE #2822: Disable 'Add to cart' button and show 'out of stock' status for out of stock product in Compare list
**Description**:
As we implemented a feature - disabled Add to cart button for out of stock products. We need to do the same in compare list.

**TO DO**:
- Disable Add to cart button for out of stock product in Compare list
- Show product status (Out of stock) instead of empty place in price column for out of stock product in Compare list

Screenshot 2021-07-01 at 11 47 52

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #2822 
Fixed Add To Cart button and price appearance on Compare page if product is out of stock.

### CODE REVIEW

File: packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js [hunk 1]
```diff
@@ -127,35 +128,52 @@ export class ProductCompareItem extends PureComponent {
...
-            >
-                <AddToCart
-                  product={ {} }
-                  groupedProductQuantity={ {} }
-                  productOptionsData={ {} }
-                  disableHandler
-                  mix={ { block: 'ProductCompareItem', elem: 'AddToCartBtn' } }
-                />
-            </Link>
+        const btn = (
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js:134]: Wondering if it won't if be better if we actually move this rendering of button into separate function, so when devs will override button they won't need to override also lines 143 - 157?

**Review by AleksandrsKondratjevs — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js (hunk 1 above)
Comment (zans-laksa) [reply packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js]: Done.

Comment (AleksandrsKondratjevs) [reply packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js]: Great. Thanks!

**Review by AleksandrsKondratjevs — APPROVED** [review]
