### PR TITLE
#4803 - added order total and subtotal fields to orders equal to 0

### LINKED ISSUE #4796: Font size of Excl.tax price for Include Order Total and Excl.tax price in Summary are wrong
**Description**:
Excl.tax price for Include Order Total is written by font with 16px high 
Excl.tax price for Include Order Total is written by font with 14px high 

**Expected behavior**:
Excl.tax price for Include Order Total and Excl.tax price in Summary are written by font with 12px high 
image

**Screenshots, Video, Logs**
image

**To Reproduce**:
in Admin:
1. Stores > Settings -  Configuration > Sales > Tax > Select 'Yes' in 'Include Tax In Order Total' field > Save 
2. Clear cache

on FE:
1. Open FE
3. Add product to cart > Open cart

### LINKED ISSUE #4803: 'Order total' is absent in summary on cart and checkout if order total equal to 0
**Description**:
'Order total' is absent in summary on cart and checkout if order total equal to 0

**Expected behavior**:
'Order total' is present in summary on cart and checkout if order total equal to 0
image

**Actual behavior**:
image

**To Reproduce**:
in Admin:
1. Stores > Settings - Configuration > Sales > Payment Methods > Zero Subtotal Checkout
2. Set YES in Enable field
3. Flush cache

on FE:
1. open product with 0 cost, for example https://scandipwapmrev.indvp.com/default/simple-sandals.html
2. Add to cart > Open cart
3. Click 'Proceed to checkout'
4. Enter required info
5. Select Free shipping Method
6. Click 'Proceed to billing'

**Actual result**:
In steps 2, 4, 6 'Order total' is absent in summary

### PR DESCRIPTION
**Pull request by MaritaKochua**
**Related issue(s):**
* Fixes #4803 
* Fixes #4796

**Problem:**
* Order total and subtotal were not appearing when the items total cost was 0. 
* Font size did not match the one in Luma. 

**In this PR:**
* Removed some conditionals and changed numbers to strings for order totals. 
* Edited font size to 12px.

### CODE REVIEW

**Review by zans-laksa — APPROVED** [review]

**Comment by carinadues** [comment]
Hey!
Please add `Excl. tax: €0.00` in the Order Total to the following:

Mini cart:
image

Cart summary:
image

Shipping:
image

Billing Step:
image

It should show if this setting is set to Yes:
image

File: packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js [hunk 1]
```diff
@@ -256,20 +256,15 @@ export class CheckoutOrderSummary extends PureComponent {
             cartTotalSubPrice
         } = this.props;
         const title = __('Order total');
-
-        if (cartTotalSubPrice) {
-            return (
+        return (
                 <CheckoutOrderSummaryPriceLine
-                  price={ grand_total }
+                  price={ grand_total.toFixed(2) }
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js:261]: What if the `grand_total` is undefined?

**Review by zans-laksa — CHANGES_REQUESTED** [review]

**Review by zans-laksa — APPROVED** [review]

**Comment by carinadues** [comment]
Hey, @MaritaKochua!

- https://github.com/scandipwa/scandipwa/issues/4796 - **Passed**
- https://github.com/scandipwa/scandipwa/issues/4803 - **Failed**:

 `Excl. tax: €0.00` is missing in the mini cart. Here's how it's on Luma:

image
Here's now: 

image

Please add, to be like here:

image

**Comment by carinadues** [comment]
Please add it here too (view previous comments for more pictures):

image

**Review by zans-laksa — APPROVED** [review]
