### PR TITLE
Upsell, Cross-sell and related product display issue

### LINKED ISSUE #1886: Related/Up-sells products disappear on product page when user adding product to cart
**Description**:
Related/Up-sells products disappear on product page when user adding product to cart

**Expected behavior**:
Related/Up-sells products are displayed

**To Reproduce**:
1. Open product page with related/up-sells products - http://scandipwapmrev.indvp.com/default/n-81-hours-cashmere-pullover
2. Notice related/up-sells products are displayed
3. Select size and color
4. Add to cart

**Actual result**:
Related/Up-sells products disappear
https://drive.google.com/file/d/1GZycPEprxqDtsMpB1jmxiaoZ87yauZXW/view?usp=sharing

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixed #1886, #1887
Took out related product update from the cart dispatcher.
Moved cross-sell product fetching and clearing to the separate methods.

### CODE REVIEW

File: src/app/component/CartItem/CartItem.container.js [hunk 1]
```diff
@@ -133,8 +142,22 @@ export class CartItemContainer extends PureComponent {
...
+
+            this.hideLoaderAfterPromise((async () => {
+                const result = await removeProduct(item_id);
+
+                if (result && updateCrossselsOnRemove) {
+                    await updateCrosssellProducts(result.items);
+                }
+
+                return result;
+            })());
```
Comment (yeegor) [inline src/app/component/CartItem/CartItem.container.js:160]: It is better to have this callback declared on the class, in the current way it is hardly extendable by e.g. plugins.

File: src/app/component/CartItem/CartItem.container.js [hunk 2]
```diff
@@ -46,6 +46,9 @@ export const mapDispatchToProps = (dispatch) => ({
     removeProduct: (options) => CartDispatcher.then(
         ({ default: dispatcher }) => dispatcher.removeProductFromCart(dispatch, options)
     ),
+    updateCrosssellProducts: (items) => CartDispatcher.then(
```
Comment (yeegor) [inline src/app/component/CartItem/CartItem.container.js:49]: So many 's' letters :D
It'd be better to `updateCrossSellProducts`

**Review by yeegor — CHANGES_REQUESTED** [review]
Seems legit, only minor detail needs improvment.

File: src/app/component/CartItem/CartItem.container.js (hunk 1 above)
Comment (zans-laksa) [reply src/app/component/CartItem/CartItem.container.js]: Done

File: src/app/component/CartItem/CartItem.container.js (hunk 2 above)
Comment (zans-laksa) [reply src/app/component/CartItem/CartItem.container.js]: Done

**Review by yeegor — APPROVED** [review]
seems legit
