### PR TITLE
value is taken from attr in fieldNumber

### LINKED ISSUE #4718: Qty is not increased in mini cart if user click on 'Add to cart' same product twice or more time
**Description**:
Qty is not increased in mini cart if user click on 'Add to cart' for same product twice or more time

**Expected behavior**:
Qty is increased in mini cart if user click on 'Add to cart' for same product twice or more time

**Screenshots, Video, Logs**
https://vimeo.com/700793010/5001f34d66

**To Reproduce**:
1. Open any product https://master.d25kd40decjpue.amplifyapp.com/default/virtual-mouse.html
2. Click 'add to cart' 
3. Click 'add to cart' same one product
4. Click on mini cart

**Actual result**:
Qty is not increase in mini cart if user click on 'Add to cart' for same product twice or more time

### PR DESCRIPTION
**Pull request by AzizKHAN030**
**Related issue(s):**
* Fixes #4718 

**Problem:**
* The number didn't update in a numberField in mini cart because the value should've been taken from attr 

**In this PR:**
* Take the value from attr if it is not undefined

### CODE REVIEW

File: packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ export class FieldNumber extends PureComponent {
                   type={ FIELD_TYPE.number }
                   readOnly
                   aria-label={ __('Value') }
-                  value={ value }
+                  value={ attr.value || value }
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js:59]: Since this is the same value as on line 46, you could reuse the `numberValue` here.

File: packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js [hunk 2]
```diff
@@ -43,7 +43,7 @@ export class FieldNumber extends PureComponent {
             isDisabled
         } = this.props;
 
-        const numberValue = +value;
+        const numberValue = +attr.value || +value;
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js:46]: What is the difference between `value` and `attr.value`?
I believe we should have only one prop for value. Having many is confusing - we never know which one is correct.

**Review by zans-laksa — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js (hunk 2 above)
Comment (AzizKHAN030) [reply packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js:46]: strange but numberField in the PDP uses value, the ones in cartOverlay and cartPage use attr.value. When I tried to pass as a value prop, the numbers stopped changing

Comment (zans-laksa) [reply packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js:46]: Please take a look at the field definition.
The `value` prop is followed by the `attr` props.
Thus the `value` will override the `attr.value`.

So please:
1. don't use `attr.value` at all
2. go through all other fields and check that they are using the `value` prop instead of `attr.value` in their definition.
3. go through all the code where fields are rendered and check that none of them is passing value inside the `attr`, but is using the `value` prop instead.

image

**Comment by zans-laksa** [comment]
Please make the same for all fields.
For textarea and text inputs too. For email felds and password fields too. For selects too.
For checkboxes and radio buttons, there should be the `checked` prop.

The idea is that `attr` is a low-level prop that contains some advanced input attributes that aren't used often.
But the value `field` is the common prop. Same `selected` or `checked` props for other field types.
Each component should get the value in an explicit way. The developer shouldn't check the source code of the project in order to know how to pass the value to the field. And all fields should work the same in terms of the interface.

**Review by zans-laksa — APPROVED** [review]
