### PR TITLE
4974 Modified same as shipping checkbox behavior

### LINKED ISSUE #4974: Checkbox 'My billing and shipping are the same' isn't selected if  default Billing address the same as Shipping Address
**Description**:
Checkbox 'My billing and shipping are the same' isn't selected if  default Billing address the same as Shipping Address

**Expected behavior**:
- Checkbox 'My billing and shipping are the same' is selected if default Billing address the same as Shipping Address
- Checkbox 'My billing and shipping are the same' isn't selected if default Billing address is not the same as Shipping Address
- Checkbox 'My billing and shipping are the same' is selected if guest or logged in user without saved addresses goes to billing step 

**To Reproduce**:
1. Open Sign in form 
2. Log in with user where Default Shipping Address = Default Billing Address
3. Open PDP
4. Add product to cart
5. Open Checkout
6. Select default Shipping&Billing address
7. Select shipping method
8. Go to billing step

**Actual result**:
Checkbox 'My billing and shipping are the same' isn't selected
https://vimeo.com/724798866/7494302244

### PR DESCRIPTION
**Pull request by denisprotassoff**
Fixes #4974 

Updated version of this PR: #5157

### CODE REVIEW

File: packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.tsx [hunk 1]
```diff
@@ -121,6 +123,14 @@ CheckoutBillingContainerState
...
     }
 
+    componentDidMount() {
+        const { isSignedIn, customer: { addresses = [] } } = this.props;
+
+        if ((isSignedIn && addresses.length === 0) || !isSignedIn) {
+            this.setState({ isSameAsShipping: true });
+        }
+    }
+
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.tsx:133]: Move this functionality to construct where initial state is set.

**Review by AleksandrsKondratjevs — CHANGES_REQUESTED** [review]
See comments

**Review by AleksandrsKondratjevs — APPROVED** [review]
