### PR TITLE
[3632] Fix green frame after wrong format error message

### LINKED ISSUE #3632: Frame around the field for loading file stay green color after error message about wrong format of file appear
**Description**:
Frame around the field for loading file stay green color after error message about wrong format of file appear

**Expected behavior**:
Frame around the field for loading file become red color after error message about wrong format of file appear

**Screenshots, Video, Logs**
image

**To Reproduce**:
1. Open product with field for loading file, for example https://master.d25kd40decjpue.amplifyapp.com/default/bottega-veneta-jodie-mini-bag.html
2. Load file with wrong format 
3. Click on 'Add to cart'
4. Observe error message and field's frame color

**Actual result**:
Frame around the field for loading file stay green color after error message about wrong format of file appear

### PR DESCRIPTION
**Pull request by Rania-Hreisa**
**Related issue(s):**
* Fixes #3632 

**Problem:**
* Missing file extension validation Rule i.e validationResponse is true.
* hasError mod is always false in Field component for all file inputs.

**In this PR:**
* Added file extension validation Rule.
* Added error message.
* Assigned the Rule on file Field.
* Fixed hasError to return true on wrong validation.

### CODE REVIEW

File: packages/scandipwa/src/util/Validator/Config.js [hunk 1]
```diff
@@ -90,5 +92,6 @@ export const VALIDATION_RULES = {
     [VALIDATION_INPUT_TYPE.date]: /\d{4}-\d{1,2}-\d{1,2}/,
     [VALIDATION_INPUT_TYPE.phone]: /^[\\+]?[(]?[0-9]{3}[)]?[-\s\\.]?[0-9]{3}[-\s\\.]?[0-9]{4,6}$/im,
     // eslint-disable-next-line max-len
-    [VALIDATION_INPUT_TYPE.emailList]: /^(([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\.([a-zA-Z]{2,5}){1,25})+([,\s]+(([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$/
+    [VALIDATION_INPUT_TYPE.emailList]: /^(([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\.([a-zA-Z]{2,5}){1,25})+([,\s]+(([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\.([a-zA-Z]{2,5}){1,25})+)*$/,
+    [VALIDATION_INPUT_TYPE.fileExtension]: /\w+\.png$|\w+\.jpg$/i
```
Comment (egils-eglitis) [inline packages/scandipwa/src/util/Validator/Config.js:96]: As we discussed in private, rename this validation to be more precise. Currently with that name we could apply this validation on other file types like documents.
Change it to something like `imageFile` so it's clear that this validation is only meant for images
Same goes for the message, etc. 
Adjust it across Your code changes

**Review by egils-eglitis — APPROVED** [review]

**Review by AleksandrsKondratjevs — APPROVED** [review]

**Comment by Elena-Evsa** [comment]
1. Boarder become red if format of file is wrong - Fixed
2. Please replace error message: "Incorrect or missing option" on message: "The file 'временное.pem' for 'upload' has an invalid extension." as it was on master https://vimeo.com/642219848/8694981c28
3. If user added in admin more allowed formats than only .png and .jpeg, for example .gif, then validation is not passed on FE for  file with .gif extension and user can not make purchase https://vimeo.com/642222744/e038853f06

**Comment by Rania-Hreisa** [comment]
**Fix is applied, waiting for retest**

Modification:
- Regenerated validation method to handle extensions from the BE.
- Fixed Error Message about Extension back to default.

File: packages/scandipwa/src/util/Validator/Validator.js [hunk 2]
```diff
@@ -86,6 +88,16 @@ export const validate = (value, rule) => {
             }
         }
     }
+
+    if (fileExtension && value !== '') {
+        const { accept } = fileExtension;
+        const acceptedExtensions = accept.split(', ');
+        const currentFileExtension = value.split('.').pop();
+
+        if (acceptedExtensions.filter((extension) => extension === currentFileExtension).length === 0) {
```
Comment (egils-eglitis) [inline packages/scandipwa/src/util/Validator/Validator.js:97]: This could be replaced with `acceptedExtensions.includes(currentFileExtension)`
A lot easier to read and shorter

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Review by egils-eglitis — CHANGES_REQUESTED** [review]

**Review by egils-eglitis — APPROVED** [review]
