### PR TITLE
Wishlist Page Crashing

### LINKED ISSUE #2759: Ooops page when opening Wishlist in my account
**Description**:
Ooops page when opening Wishlist in my account

**Expected behavior**:
No errors

**To Reproduce**:
1. Log in 
2. Open Wishlist (add products to a wishlist if user don't have products there)

**Actual result:**:
Ooops page opens
Error message '_TypeError: Cannot read property 'find' of undefined_' appears in the console
Screenshot 2021-06-11 at 13 18 59

**Additional context**:

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #2759
Fixed wishlist page crashing.
Fixed some errors from the console.

### CODE REVIEW

File: packages/scandipwa/src/component/ProductCard/ProductCard.container.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ export class ProductCardContainer extends PureComponent {
 
         // if 'Product Use Categories' is enabled then use the current window location to see if the product
         // has any url_rewrite for that path. (if not then just use the default url)
-        const rewriteUrl = url_rewrites.find(({ url }) => url.includes(productUrl)) || {};
+        const rewriteUrl = url_rewrites?.find(({ url }) => url.includes(productUrl)) || {};
```
Comment (IvansZuks) [inline packages/scandipwa/src/component/ProductCard/ProductCard.container.js:123]: Should here be this `?`

Comment (zans-laksa) [reply packages/scandipwa/src/component/ProductCard/ProductCard.container.js]: You are right. Default values are much better. Fixed.

**Review by IvansZuks — APPROVED** [review]
