### PR TITLE
#3882 - Set check before history push if it is overlay

### LINKED ISSUE #3882: 'Forgot password' and 'Create account' popup are not opened if user situated on create account page
**Description**:
'Forgot password' and 'Create account' popup are not opened if user situated on create account page

**Expected behavior**:
'Forgot password' and 'Create account' popup are opened if user situated on create account page

**Screenshots, Video, Logs**
https://vimeo.com/654101297/066434f88e

**To Reproduce**:
1. Open login page 
https://master.d25kd40decjpue.amplifyapp.com/default/customer/account/login
2. Click on Account sign > Forgot password

**Actual result**:
Forgot password popup is not opened if user situated on create account page

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
**Related issue(s):**
* Fixes #3882 

**Problem:**
* MyAccountOverlay doesn't check if it is overlay before clicking on forgot passoword so it tries to redirect to other page and closes overlay

**In this PR:**
* Set check if it is overlay

### CODE REVIEW

File: packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js [hunk 1]
```diff
@@ -175,7 +176,10 @@ export class MyAccountOverlayContainer extends PureComponent {
             }
         }
 
-        if (newMyAccountState !== STATE_LOGGED_IN && pathname.includes(ACCOUNT_URL)) {
+        if (newMyAccountState !== STATE_LOGGED_IN
```
Comment (zans-laksa) [inline packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js:179]: Please put the condition to a new line.

**Review by zans-laksa — APPROVED** [review]
