### PR TITLE
Order popup FE

### LINKED ISSUE #2271: Order popup is empty if purchased product is deleted/disabled
**Description**:
Order popup is empty if purchased product is deleted/disabled

**Expected behavior**:
Order popup opens with all data

**To Reproduce**:
1. Log in ddd@gmail.com/Scandipwa123  OR log in -> complete order -> delete/disable purchased product in Admin panel 
2. Open Order list
3. Open Order #000000374

**Actual result:**:
Order popup is empty
image

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #2271
Fixed some console errors

Related PR: scandipwa/quote-graphql/pull/75

### CODE REVIEW

**Review by yeegor — APPROVED** [review]

File: packages/scandipwa/src/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ export const OrderDispatcher = import(
 export const mapStateToProps = (state) => ({
     order: state.OrderReducer.order,
     payload: state.PopupReducer.popupPayload[ORDER_POPUP_ID] || {},
-    display_tax_in_shipping_amount: state.ConfigReducer.cartDisplayConfig.display_tax_in_shipping_amount
+    display_tax_in_shipping_amount: state.ConfigReducer.cartDisplayConfig.display_tax_in_shipping_amount || ''
```
Comment (yeegor) [inline packages/scandipwa/src/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js:35]: I think it's better to have this value set as default value in the corresponding reducer's `getInitialState`.
Please provide this change and then we'll merge!

**Review by yeegor — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js (hunk 1 above)
Comment (zans-laksa) [reply packages/scandipwa/src/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js]: Done.

**Review by yeegor — APPROVED** [review]
