### PR TITLE
Respect price tax diplay settings

### LINKED ISSUE #1508: Including and Excluding Tax (Price display setting) / M2 Support
**Description**:
With this setting set, the product prices and shipping prices are displayed with both including tax and excluding tax on the storefront.
https://docs.magento.com/user-guide/configuration/sales/tax.html#price-display-settings

**TODO**:
Implement support for the feature

### LINKED ISSUE #1625: Price including Tax is always displayed on category and product pages even we set excluding tax in admin panel
**Description**:
Price including Tax is always displayed on category and product pages even we set excluding tax in admin panel

**Expected behavior**:
Price excluding Tax is displayed

**To Reproduce**:
1. Open Admin panel -> go to Stores -> Settings - > Configuration -> Sales and choose Tax
2. Select Excluding Tax in Display Product Prices in Catalog
3. Tap 'Save' -> Flush Cache Storage
4. Open website -> Open category -> open product page

**Actual result:**:
Price including Tax is always displayed

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
fixes #1508
fixes #1625 

Related PR :
https://github.com/scandipwa/store-graphql/pull/9
https://github.com/scandipwa/catalog-graphql/pull/85

Adds check if price in catalog and shipping price should excl/incl tax or should be displayed both. 
Atm magento 2 is not providing excl tax price in graphql, so while it is not supported added excl tax price in price range response.

### CODE REVIEW

File: packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js [hunk 1]
```diff
@@ -51,14 +53,12 @@ export class CheckoutDeliveryOption extends PureComponent {
...
-                    display_tax_in_shipping_amount
-                } = {},
                 quote_currency_code
-            }
+            },
+            displayTaxInPrice
         } = this.props;
 
-        if (display_tax_in_shipping_amount === DISPLAY_CART_TAX_IN_SHIPPING_EXL_TAX) {
+        if (displayTaxInPrice === DISPLAY_SHIPPING_PRICES_EXCL_TAX) {
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js:61]: Display Shipping Prices in Price Display Settings defines if shipping price will include/exclude tax or display both.

**Review by alfredsgenkins — APPROVED** [review]
