### PR TITLE
Fix issue with swatch_data selection for product cards

### LINKED ISSUE #1996: User redirect to Ooops page if we set Used in product listing to No and opened category or confg product with related products
**Description**:
User redirect to Ooops page if we set Used in product listing to No and opened category or confg product with related products

**Expected behavior**:
3. Category page opens
4. Product page opens

**To Reproduce**:
1. Open admin -> stores -> attributes -> product -> color attribute -> storefront properties -> set used in product listing to no
2. clear cache
3. open category page (for example women)
4. Open config product page (with related products) - https://3-3-0-rc.d25kd40decjpue.amplifyapp.com/default/n-dine-n-dance-cashmere-pullover

**Actual result:**:
User redirected to Ooops page
image

### LINKED ISSUE #2041: Attribute values (color with images) are missing in the product cards on category page if Used in Product Listing is set to yes
**Description**:
Attribute values (color with images) are missing in the product cards on category page if Used in Product Listing is set to yes

**Expected behavior**:
Attribute values are always present in the product cards 

**To Reproduce**:
1. Open admin panel->stores->attributes->product->colors with images attribute->storefront properties->set used in product listing to yes
2. Clear cache
3. Open women or kids category

**Actual result**:
Attribute values are missing in the product cards 
image

**Additional context**:
Attribute in the Admin panel: https://scandipwapmrev.indvp.com/admin/catalog/product_attribute/edit/attribute_id/224/key/d8d31164d7df1b82be92927b6a3b3cf138564b18c0b7cd1089ea06d5600757f6/active_tab/front/back/edit/

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
Fixes #2041 
Fixes #1996

Previously for product cards it was getting first element from configurable_options property and if it was not containing swatch data then product card was without visual attributes. 
Example:
```
configurable_options: {
  { label: size, swatch_data: null, type null }
  { label: color_images, swatch_data: {....}, type: 2 }
}
```
It was getting only size attribute and since there is no swatch_data: result is empty for product card.

Also implemented support for images type.

### CODE REVIEW

**Comment by AleksandrsKondratjevs** [comment]
> Minor coding style comments.

Done!

File: packages/scandipwa/src/component/ProductCard/ProductCard.component.js [hunk 1]
```diff
@@ -206,7 +210,23 @@ export class ProductCard extends PureComponent {
...
+            src={ `/media/attribute/swatch/swatch_thumb/110x90${value}` }
+            alt={ label }
+          />
+        );
+    }
+
+    renderVisualOption = ({ label, value, type }, i) => {
+        if (type === OPTION_TYPE_IMAGE) {
+            return this.renderImageVisualOption(label, value, i);
+        }
```
Comment (yeegor) [inline packages/scandipwa/src/component/ProductCard/ProductCard.component.js:228]: I have the hardcore-est deja vu about this.

**Review by yeegor — APPROVED** [review]
