### PR TITLE
Account Confirmation Form Validation And Submission

### LINKED ISSUE #2085: Never-ending loader on confirm your account page if user entered <8symbols in the field and clicked confirm account
**Description**:
Never-ending loader on confirm your account page if user entered <8symbols in the field and clicked confirm account 

**Expected behavior**:
Error message appears 'Incorrect data! Please resolve all field validation errors.'

**To Reproduce**:
1. Open Admin panel -> go to Stores > Settings > Configuration -> Customers -> Customer Configuration -> Create New Account Options section -> Select 'Yes' in Require Emails Confirmation field
2. Tap 'Save' -> Flush Cache Storage
3. Open website
4. Create account
5. Open the email
6. Open Confirmation link
7. Enter invalid password (password length < 8 characters)
8. Click Confirm account

**Actual result**:
Never-ending loader and error message appears in the console
image

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #2085
Fixed account confirmation form validation.
Fixed account confirmation form submission steps on failure.
Fixed field invalid prop type error from the console.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
Now all fields have red frame + new error in console
image

File: packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js [hunk 1]
```diff
@@ -176,7 +176,12 @@ export class MyAccountDispatcher {
             /** @namespace Store/MyAccount/Dispatcher/confirmAccountFetchMutationThen */
             () => dispatch(showNotification('success', __('Your account is confirmed!'))),
             /** @namespace Store/MyAccount/Dispatcher/confirmAccountFetchMutationError */
-            () => dispatch(showNotification('error', __('Something went wrong! Please, try again!')))
+            (err) => {
+                const { message } = err[0] || err;
+                return dispatch(
+                    showNotification('error', message || __('Something went wrong! Please, try again!'))
```
Comment (yeegor) [inline packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js:182]: Prefer default values for destructured variables, where it is possible (`const {a=1} = options`)

**Review by yeegor — APPROVED** [review]
