### PR TITLE
Comparable Attribute Values

### LINKED ISSUE #1999: ID option is displayed for specific attributes in compare list
**Description**:
ID option is displayed for specific attributes in compare list

**Expected behavior**:
New multiple attribute options - 1,2,3,4,5
test attribute - green

**To Reproduce**:
1. open product - https://3-3-0-rc.d25kd40decjpue.amplifyapp.com/default/28-grouped-product.html
2. Add to compare list
3. open compare list

**Actual result**:
New multiple attribute options - 5512,5513 and etc
test attribute 5510
image

**Additional context**:
the same situation with an attribute - color with images

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #1999
Fixed comparable attribute values.

### CODE REVIEW

File: packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js [hunk 1]
```diff
@@ -90,12 +91,31 @@ export class ProductCompareContainer extends PureComponent {
...
 
+    getAttributeValue(value, options) {
+        return options[value]?.label || value || null;
+    }
+
+    getMultiSelectAttributeValue(value, options) {
+        return value
+            .split(/,\s*/)
+            .map((v) => this.getAttributeValue(v, options))
+            .filter((v) => !!v)
```
Comment (yeegor) [inline packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js:115]: Alternatively, you may use `something.filter(x => x)` or `something.filter(Boolean)`, but this is fine as well.

**Review by yeegor — APPROVED** [review]
Good!
