### PR TITLE
#4850 change error to the 404 page

### LINKED ISSUE #4850: Ooops page when logged in user is opening /wishlist page if wishlist is disabled
**Description**:
Ooops page when logged in user is opening /wishlist page if wishlist is disabled

**Expected behavior**:
404 page 

**To Reproduce**:
1. Stores -> Customer -> Wishlist
2. Set Enabled to No 
3. Save
4. Clear Cache

FE:
5. Open Sign in form
6. Log in
7. Open wishlist page /wishlist

**Actual result**:
Ooops page opens
Error message 'TypeError: Cannot read properties of undefined (reading 'title')' appears in the console
Screenshot 2022-05-30 at 12 30 02

### PR DESCRIPTION
**Pull request by MaritaKochua**
**Related issue(s):**
* Fixes #4850 

**Problem:**
* Page rendered error message instead of the styled 404 page.

**In this PR:**
* Redirected to 404 page.

### CODE REVIEW

File: packages/scandipwa/src/route/MyAccount/MyAccount.component.js [hunk 1]
```diff
@@ -166,6 +167,10 @@ export class MyAccount extends Component {
             return this.renderLoginOverlay();
         }
 
+        if (!tabMap[activeTab]) {
+            return <NoMatch />;
+        }
```
Comment (zans-laksa) [inline packages/scandipwa/src/route/MyAccount/MyAccount.component.js:172]: The wishlist page availability is configured from the admin panel.
Please fetch this setting from the BE and check it here.

**Review by zans-laksa — CHANGES_REQUESTED** [review]

**Review by zans-laksa — APPROVED** [review]
