### PR TITLE
[3886] modified logic to show locked account error

### LINKED ISSUE #3886: Account is locked when changing password in my account and user entered invalid current password
**Description**:
Account is locked when changing password in my account and user entered invalid current password

**Expected behavior**:
User automatically log out and Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' appears 

**To Reproduce**:
1. Open Sign in form
2. Log in
3. Open Account information page in my account 
4. Select 'Change password' checkout 
5. Enter invalid current password
6. Enter new and confirm password

**Actual result**:
Error message 'The account is locked.' appears
Screenshot 2021-12-07 at 14 14 05

### PR DESCRIPTION
**Pull request by pablobentivengo**
**Related issue(s):**
* Fixes #3886 

**Problem:**
* Two error messages are shown when user is redirected to 'Sign in' page
https://vimeo.com/680376033/01df6ad163
Only Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' should appear
* Mobile: extra error and success messages appears. Only Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' should appear.
https://vimeo.com/680377529/f1f2029860 - IOS, on Android success message absent

**In this PR:**
* MyAccountInformation.container, modified onSubmit logic, and if user gets locked updates MyAccount ReduxStore
* MyAccount route, handles if user is locked and redirects to MyAccountLogin
* MyAccountLogin if is redirect from locked user show error message

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
1.Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' is missing for the first time
**Steps:**
1. Open Website in incognito mode
2. Log in
3. Open Account Information page
4. Enter invalid current password
5. Enter new and confirm password
6. Save
7. Repeat previous step 3 times

**Actual result:**
Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' is missing 
**Expected result:**
Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' is displayed
**Notes:**
Error message appears when doing the same steps for the second time

**Comment by pablobentivengo** [comment]
Not ready

File: packages/scandipwa/src/route/MyAccount/MyAccount.container.js [hunk 1]
```diff
@@ -486,17 +489,18 @@ export class MyAccountContainer extends PureComponent {
...
             ? appendWithStoreCode(ACCOUNT_LOGIN_URL)
-            : replace(/\/customer\/account\/.*/, ACCOUNT_LOGIN_URL);
+            : replace(/\/customer\/account\/?.*/i, ACCOUNT_LOGIN_URL);
 
-        history.push({
-            pathname: path,
-            state: { isFromLocked: true }
-        });
+        history.replace({ pathname: path, state: { isFromLocked: true } });
+        showNotification('error', __(LOCKED_ACCOUNT_ERROR_MESSAGE));
```
Comment (riha112) [inline packages/scandipwa/src/route/MyAccount/MyAccount.container.js:501]: `__(LOCKED_ACCOUNT_ERROR_MESSAGE)` this won't work; `__(...)` function requires first parameter to be direct string otherwise it will not be added to translation files.

In this example you should move translation to const.... `export const LOCKED_ACCOUNT_ERROR_MESSAGE = __("...")`
and then use `showNotification('error', LOCKED_ACCOUNT_ERROR_MESSAGE);`

File: packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.container.js [hunk 2]
```diff
@@ -145,47 +140,40 @@ export class MyAccountInformationContainer extends PureComponent {
...
-                const message = 'The account sign-in was incorrect or your account is disabled temporarily.'
-                + 'Please wait and try again later.';
-
-                showErrorNotification(message);
-                this.handleLogout({ isFromLocked: true });
-            }
+            history.push({ pathname: appendWithStoreCode(ACCOUNT_URL) });
         }
+
+        showSuccessNotification('You saved the account information.');
```
Comment (riha112) [inline packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.container.js:176]: Requires translation: `__('You saved the account information.')`

**Review by riha112 — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/route/MyAccount/MyAccount.container.js (hunk 1 above)
Comment (pablobentivengo) [reply packages/scandipwa/src/route/MyAccount/MyAccount.container.js]: Done

File: packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.container.js (hunk 2 above)
Comment (pablobentivengo) [reply packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.container.js]: done

**Review by riha112 — APPROVED** [review]
