### PR TITLE
Fixed category page placeholders

### LINKED ISSUE #5334: Placeholders from PLP shown on CMS page if user open it from default menu manager
**Steps to reproduce:**
in Admin:
1. Click Catalog > Category
2. Select any Category prepared for CMS content Like 'About us'
3. Click 'Display Settings'
4. Select Display Mode = Static block only
5. Save
on FE:
6. Open 'About Us' page/category from menu

**Actual result**
Placeholders from PLP shown on CMS page if user open it from default menu manager

**Expected result**
Placeholders from CMS page are shown on 'About Us' page/category if user opened it from top menu
image

**Testing details**
**Screenshot/Screencast**
https://vimeo.com/778070768/57a8606108

### PR DESCRIPTION
**Pull request by denisprotassoff**
Fixes #5334.

Issue: category page was showing incorrect placeholders for static content only.

In this PR: added displayMode to menu items to load correct placeholders.

### CODE REVIEW

**Review by AleksandrsKondratjevs — CHANGES_REQUESTED** [review]
See comments

File: packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.tsx [hunk 1]
```diff
@@ -161,16 +162,31 @@ export class UrlRewritesContainer extends PureComponent<UrlRewritesContainerProp
...
+
+                    if (category && category !== true) {
+                        return {
+                            categoryIds: category,
+                            displayMode,
+                        };
+                    }
                 }
 
                 return {};
```
Comment (AleksandrsKondratjevs) [inline packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.tsx:183]:
```javascript
if (!history) {
    return {};
}

...
```
Less nesting :))

**Review by AleksandrsKondratjevs — APPROVED** [review]

**Review by AleksandrsKondratjevs — APPROVED** [review]
