### PR TITLE
Authentication And Quote Id Fixes

### LINKED ISSUE #2568: Issues connected with authorization
**1. Description**:
Can't scroll page if user opens order in my account and Cookie Lifetime ends

**Expected behavior**:
Can scroll page

**To Reproduce**:
1. Log in
2. Open order list
3. Wait when the Cookie Lifetime ends
4. Open order

**Actual result**:
User redirects to Homepage BUT user can't scroll page

**Additional conteext**:
You can change Cookie Lifetime in Admin panel -> Stores -> General -> Web -> Cookie Lifetime
_____________________________

**2. Description**:
Mobile: User sees blank page ±3sec after logged in

**Expected behavior**:
My account appears after user logged in and blank page is missing if it's possible
If not -> Add loader icon 

**To Reproduce**:
1. Log in

**Actual result**:
User sees blank page ±3sec

**Additional context**:
Seems it happens because of cart takes a long time to load
__________________________________

**3. Description**:
User doesn't see notification message 'Your session is over, you are logged out!' if Cookie Lifetime ends and he opens 404 page

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed

**To Reproduce**:
1. Log in
2. Wait when the Cookie Lifetime ends
3. Open not existing page (404)

**Actual result**:
The notification message 'Your session is over, you are logged out!' is missing

__________________________________

**4. Description**:
User stays on the shipping step if Cookie Lifetime ends

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed and user redirects to /account/login
Also do the same if user located on my account pages

**To Reproduce**:
1. Log in
2. Add product to cart
3. Go to shipping step
4. Fill form
5. Wait when the Cookie Lifetime ends
6. Go to billing step

**Actual result**:
User stays on the shipping step. All products are missing 
image

**Additional context**:
If user tried to fill form, ooops page opens
image

__________________________________

**5. Description**:
Error message 'Current user isn't authorized' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user changes password

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed and user redirects to /account/login

**To Reproduce**:
1. Log in
2. Open my account
3. Click change password
4. Wait when the Cookie Lifetime ends
5. Enter current and new password
6. Click change password

**Actual result**:
Error message 'Current user isn't authorized' is displayed and user stays on the same page in my account
image

**Additional context**:
Steps:
Close change password pup up
Open Edit details
Change
Click Save 
=> user redirects to homepage -> can't scroll page

__________________________________

**6. Description**:
Error message 'Authorization unsuccessful' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user shares wishlist

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed and user redirects to /account/login

**To Reproduce**:
1. Log in
2. Add product to Wishlist
3. Open Wishlist
4. Click Share Wishlist
5. Enter email
6. Wait when the Cookie Lifetime ends
7. Clips send

**Actual result**:
Error message 'Authorization unsuccessful' is displayed and user stays on the same page in my account
image

__________________________________

**7. Description**:
guest_quote_id disappears if not logged in user completed order

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Add product to card
2. Complete order

**Actual result**:
guest_quote_id disappears
User can't add product to cart
Token appears when refreshing page 

**Additional context**:
If user logged in and complete order -> guest_quote_id chenges
__________________________________

**8. Description**:
Sometimes logged user sees error message 'Internal server error' when adding product to cart
I didn’t find specific steps to reproduce it. If user logged out , he can add product to cart

### PR DESCRIPTION
**Pull request by zans-laksa**
Fixes #2568
Added some authentication and quote id related fixes.

### CODE REVIEW

**Comment by aleksandrakorolova** [comment]
2.Now : loader -> success message -> blank page -> my account https://drive.google.com/file/d/1D2JTtgHF0jJFNLhq8iFuMlPn2gjcvYnH/view?usp=sharing
Can we do how it works early? loader -> my account and success message

5. Error message 'Current user isn't authorized' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user changes password -  can reproduce

6.Error message 'Authorization unsuccessful' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user shares wishlist -  can reproduce

8. Can reproduce with account ddd@gmail.com / Scandipwa1234

**Comment by aleksandrakorolova** [comment]
2. Fixed
8. Will create a separate task for this issue
9. Fixed 
10. Sometimes never-ending loader when user create an account (2 cases: create account after checkout and not)
image
image
image

File: packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js [hunk 1]
```diff
@@ -112,6 +112,7 @@ export class MyAccountSignInContainer extends PureComponent {
         try {
             await signIn(fields);
             onSignIn();
+            setLoadingState(false);
```
Comment (IvansZuks) [inline packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js:115]: This can be moved after try catch block

File: packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js [hunk 2]
```diff
@@ -39,9 +53,23 @@ export class LoginAccountContainer extends MyAccountOverlayContainer {
...
+        }
 
         setHeaderState({ name: CUSTOMER_ACCOUNT, title: __('Sign in') });
+        toggleBreadcrumbs(false);
+    }
+
+    componentDidUpdate(prevProps, prevState) {
+        if (isSignedIn()) {
+            history.push(appendWithStoreCode('/'));
+            return;
```
Comment (IvansZuks) [inline packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js:69]: Missed white line before return

File: packages/scandipwa/src/route/MyAccount/MyAccount.container.js [hunk 3]
```diff
@@ -272,7 +286,6 @@ export class MyAccountContainer extends PureComponent {
 
         if (activeTab !== MY_WISHLIST) {
             this.changeDefaultHeaderState();
-
```
Comment (IvansZuks) [inline packages/scandipwa/src/route/MyAccount/MyAccount.container.js:275]: We should leave this white line

**Review by IvansZuks — CHANGES_REQUESTED** [review]

File: packages/scandipwa/src/route/MyAccount/MyAccount.container.js (hunk 3 above)
Comment (zans-laksa) [reply packages/scandipwa/src/route/MyAccount/MyAccount.container.js]: Fixed

**Review by IvansZuks — APPROVED** [review]
